version: "3"

services:
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      - MONGO_URI=${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_URI}
      - PORT=${PORT}
      - VIRTUAL_HOST=${SERVER_VIRTUAL_HOST}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./server/src:/app/server/src
    # command: node src/server.js
    depends_on:
      - db
    links:
      - db
    restart: always
    
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on: 
      - server
      - db
    links:
      - server
    restart: always
    
  db:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command: mongod --port ${MONGO_PORT}
    volumes:
      - board-dbdata:/data/db
      
volumes:
  ? board-dbdata